<?php
/**
 * Copyright © Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magmodules\Channable\Block\Adminhtml\System\Config\Button\Selftest;

/**
 * @see \Magmodules\Channable\Block\Adminhtml\System\Config\Button\Selftest
 * @var Selftest $block
 */
?>

<div id="mm-ui-result_test-modal" 
     data-mm-ui-endpoind-url="<?= $block->escapeUrl($block->getSelftestUrl()) ?>">
    <div id="mm-ui-result_test">
        <ul class="result"></ul>
    </div>
</div>
