<?php
/**
 * Copyright © 2017 Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 * @var $block Magmodules\Channable\Block\Adminhtml\System\Config\Form\OrderHooks
 */
?>
<?php if ($webhooks = $block->getConfigData()) { ?>
    <div class="mm-block-channable-feeds">
        <table class="mm-block-channable-feed-table">
            <thead>
                <span class="title">Order Webhooks</span>
                Each store view will have their own Channable Order webhook.
            </thead>
            <tbody>
                <?php foreach ($webhooks as $webhook) { ?>
                    <tr>
                        <td style="width: 25%;">
                            <p><?php echo $webhook['name']; ?></p>
                            <p>
                                <small><?php echo $webhook['code']; ?></small>
                            </p>
                        </td>
                        <td style="width: 35%;">
                            <?php if (!empty($webhook['webhook_url'])) { ?>
                                <p><a class="webook" href="<?php echo $webhook['webhook_url']; ?>" target="_blank"><?php echo $webhook['webhook_url']; ?></a></p>
                                <p><a class="orderstatus" href="<?php echo $webhook['status_url']; ?>" target="_blank"><?php echo $webhook['status_url']; ?></a></p>
                            <?php } ?>
                        </td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
<?php } ?>