<?php
/**
 * Copyright © Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/**
 * @var \Magmodules\Channable\Block\Info\Channable $block
 * @see \Magmodules\Channable\Block\Info\Channable
 */
$specificInfo = $block->getSpecificInformation();
?>
<?php echo $block->escapeHtml($block->getMethod()->getTitle()); ?>
<table class="data-table admin__table-secondary channable">
    <tbody>
        <?php if ($channelName = $this->getInfo()->getAdditionalInformation('channel_name')): ?>
            <tr>
                <th><?= __('Channel Name'); ?></th>
                <td><?= $channelName; ?></td>
            </tr>
        <?php endif; ?>
        <?php if ($channelLabel = $this->getInfo()->getAdditionalInformation('channel_label')): ?>
            <tr>
                <th><?= __('Channel Label'); ?></th>
                <td><?= $channelLabel; ?></td>
            </tr>
        <?php endif; ?>
        <?php if ($channelId = $this->getInfo()->getAdditionalInformation('channel_id')): ?>
            <tr>
                <th><?= __('Channel ID'); ?></th>
                <td><?= $channelId; ?></td>
            </tr>
        <?php endif; ?>
        <?php if ($shipmentPromise = $this->getInfo()->getAdditionalInformation('shipment_promise')): ?>
            <tr>
                <th><?= __('Shipment Promise'); ?></th>
                <td><?= $shipmentPromise; ?></td>
            </tr>
        <?php endif; ?>
        <?php if ($channelCustomerNumber = $this->getInfo()->getAdditionalInformation('channel_customer_number')): ?>
            <tr>
                <th><?= __('Channel Customer Number'); ?></th>
                <td><?= $channelCustomerNumber; ?></td>
            </tr>
        <?php endif; ?>
        <?php if ($externalArticleNumbers = $this->getInfo()->getAdditionalInformation('external_article_numbers')): ?>
            <tr>
                <th><?= __('External Article Number(s)'); ?></th>
                <td>
                    <div class="channable-tooltip"><?= __('Show Numbers'); ?>
                        <span>
                            <table class="channable-delivery-info-table">
                                <tr>
                                    <td><?= nl2br($externalArticleNumbers); ?></td>
                                </tr>
                            </table>
                        </span>
                    </div>
                </td>
            </tr>
        <?php endif; ?>
        <?php if ($channableId = $this->getInfo()->getAdditionalInformation('channable_id')): ?>
            <tr>
                <th><?= __('Channable ID'); ?></th>
                <td><?= $channableId; ?></td>
            </tr>
        <?php endif; ?>
        <?php if ($commission = $this->getInfo()->getAdditionalInformation('commission')): ?>
            <tr>
                <th><?= __('Commission'); ?></th>
                <td><?= $commission; ?></td>
            </tr>
        <?php endif; ?>
        <?php if ($delivery = $this->getInfo()->getAdditionalInformation('delivery')): ?>
            <tr>
                <th><?= __('Delivery'); ?></th>
                <td>
                    <div class="channable-tooltip"><?= __('Show Delivery Periods'); ?>
                        <span>
						<table class="channable-delivery-info-table">
							<?php foreach ($delivery as $item): ?>
                                <tr>
									<td><?= $item['title']; ?></td>
									<td><?= $item['ean']; ?></td>
									<td><?= $item['delivery_period']; ?></td>
								</tr>
                            <?php endforeach; ?>
						</table>
					    </span>
                    </div>
                </td>
            </tr>
        <?php endif; ?>
        <?php if ($memo = $this->getInfo()->getAdditionalInformation('memo')): ?>
            <tr>
                <th><?= __('Memo'); ?></th>
                <td>
                    <div class="channable-tooltip"><?= __('Show Memo Data'); ?>
                        <span>
                            <table class="channable-delivery-info-table">
                                <tr>
                                    <td><?= nl2br($memo); ?></td>
                                </tr>
                            </table>
                        </span>
                    </div>
                </td>
            </tr>
        <?php endif; ?>
    </tbody>
</table>
<?php echo $block->getChildHtml() ?>
