<?php
/**
 * Copyright © 2019 Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/**
 * @var \Magmodules\Channable\Block\Info\Channable $block
 * @see \Magmodules\Channable\Block\Info\Channable
 */
?>
<?= $block->escapeHtml($block->getMethod()->getTitle()); ?>{{pdf_row_separator}}

<?php if ($specificInfo = $block->getSpecificInformation()):?>
    <?php foreach ($specificInfo as $label => $value):?>
        <?= $block->escapeHtml($label) ?>:
        <?= $block->escapeHtml(implode(' ', $block->getValueAsArray($value)));?>
        {{pdf_row_separator}}
    <?php endforeach; ?>
<?php endif;?>

<?= $block->escapeHtml(implode('{{pdf_row_separator}}', $block->getChildPdfAsArray())); ?>
