<?php
/**
 * Copyright © Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var $block Magmodules\Channable\Block\Adminhtml\System\Config\Form\Table\Orders
 */
?>
<tr class="channable-table" id="row_<?= $block->escapeHtml($block->getHtmlId()); ?>">
    <td class="label"></td>
    <td class="value">
        <table class="data-grid" id="<?= $block->escapeHtml($block->getId()) ?>_table">
            <thead>
            <th>
                <?= $block->escapeHtml(__('Store')) ?>
            </th>
            <th>
                <?= $block->escapeHtml(__('Webhook')) ?>
            </th>
            <th>
                <?= $block->escapeHtml(__('Test')) ?>
            </th>
            </thead>
            <tbody>
            <?php foreach ($block->getStoreData() as $store): ?>
                <tr>
                    <td>
                        <?= $block->escapeHtml($store['name']); ?>
                    </td>
                    <td>
                        <textarea title="webhook" disabled><?= $block->escapeUrl($store['webhook_url']); ?></textarea>
                    </td>
                    <td>
                        <a href="<?= $block->escapeUrl($block->getTestOrderUrl((int)$store['store_id'])); ?>">
                            <?= $block->escapeHtml(__('Import Test Order')) ?>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </td>
    <td></td>
</tr>
