name: setup:di:compile

on: pull_request

jobs:
  build:
    strategy:
      matrix:
        include:
          - PHP_VERSION: php71-fpm
            MAGENTO_VERSION: 2.3.3
          - PHP_VERSION: php73-fpm
            MAGENTO_VERSION: 2.3.6-p1
          - PHP_VERSION: php74-fpm
            MAGENTO_VERSION: 2.4.2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Start Docker
        run: docker run --detach --name magento-project-community-edition michielgerritsen/magento-project-community-edition:${{ matrix.PHP_VERSION }}-magento${{ matrix.MAGENTO_VERSION }}

      - name: Upload our code into the docker container
        run: docker cp $(pwd) magento-project-community-edition:/data/extensions/

      - name: Install the extension in Magento
        run: docker exec magento-project-community-edition composer require magmodules/magento2-channable:@dev

      - name: Run setup:di:compile
        run: docker exec magento-project-community-edition php bin/magento setup:di:compile
